### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by comiclandapp** [andrej8888/CoordinatorArticle#1]
Hi, there. I'm trying out different coordinator patterns and found your [article](https://www.goodrequest.com/blog/coordinator-pattern) very interesting. In putting together your [board](https://www.thiscodeworks.com/boards/61a5d7784663a000156092fd) I can't find the Step class. Do you have a minute to upload the final working project? Thanks a lot. Regards.

**Comment by andrej-jasso** [comment]
Hi there,

Thanks for noticing I must've forgotten to push it, here you go.

Have a nice day 👍
