### ISSUE TITLE
Coordinator Dropping out of memory before I'm done using it

### ISSUE THREAD

**Issue by Walker123t** [andrej8888/CoordinatorArticle#2]
Was curious how you guys handled keeping certain coordinators in memory. If you kept a reference to them on the view controller, or if you added an array of children to your Coordinator class

**Comment by andrej-jasso** [comment]
@Walker123t so basically we would keep an array of coordinators in the app coordinator and remove them before a coordinator is dealocated. 


```
class Coordinator<Step>: GoodCoordinator<Step>, CoordinatorProtocol {

    func addCoordinator(coordinator: Coordinator<Step>) {
        parentStepCoordinator?.addCoordinator(coordinator: coordinator)
    }

    func removeCoordinator(coordinator: Coordinator<Step>) {
        parentStepCoordinator?.removeCoordinator(coordinator: coordinator)
    }

```
 And then in app coordinator you would add and remove from the add in its implementation of those methods
 
```
 final class AppCoordinator: Coordinator<AppStep> {

    // MARK: - Variables

    private var coordinators = [GoodCoordinator<AppStep>]()
    
    override func addCoordinator(coordinator: GoodCoordinator<AppStep>) {
        coordinators.append(coordinator)
    }

    override func removeCoordinator(coordinator: GoodCoordinator<AppStep>) {
        if let index = coordinators.firstIndex(where: { $0 == coordinator }) {
            coordinators.remove(at: index)
        }
    }
```

Next we established a parent coordinator init parameters in every child coordinator so it gets called recursivelly untill the AppCoordinator

And as last we created some viewcontroller coordinator binding where if the controller calls deinit the coordinator will call this removeCoordinator method and therefore loose the last reference and dealocate as well
